### Create New Idea
POST http://localhost:8000/createIdea
Content-Type: application/json

{
	"title": "consume quas",
	"type": "existence",
	"status": "ongoing",
	"when": null
}

### Get All Ideas
GET  http://localhost:8000/getIdeas/ongoing
Content-Type: application/json

### Change Idea Status
PATCH  http://localhost:8000/changeStatus
Content-Type: application/json

{
	"id": 1,
	"status": "fullfilled",
	"completionTime": "Thu Jul 11 2024 21:47:01 GMT+03:00 (Eastern European Summer Time)"
}