### Create New Idea
POST http://localhost:8000/createIdea
Content-Type: application/json

{
	"title": "test 4",
	"type": "Study",
	"status": "Fresh",
	"when": null
}

### Get All Ideas
GET  http://localhost:8000/getAllIdeas
Content-Type: application/json

### Store ideas
POST http://localhost:8000/storeIdeas
Content-Type: application/json

{
	"ideas": [
	{
	"title": "test title",
	"type": "test type",
	"status": "test",
	"when": null
	},
	{
	"title": "test title",
	"type": "test type",
	"status": "test",
	"when": null
	},
	{
	"title": "test title",
	"type": "test type",
	"status": "test",
	"when": null
	}
	]
}